[package]
name = "rasm"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
backtrace = "0.3"
chrono = "0.4"
env_logger = "0.9"
linked-hash-map = "0.5"
log = "0.4"
pad = "0.1"
regex = "1.6"
strum = "0.23"
strum_macros = "0.23"
tempdir = "0.3"

[dev-dependencies]
test_bin = "0.4"
test-log = "0.2"
