[workspace]
members = ["core",  "parser", "rasm", "server", "utils", "showlog"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.0"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
rasm-core = { path = "./core" }
rasm-parser = { path = "./parser" }
rasm-server = { path = "./server" }
rasm-showlog = { path = "./showlog" }
rasm-ui = { path = "./ui" }
rasm-utils = { path = "./utils" }

auto_impl = "1.3.0"
backtrace = "0.3"
clap = "4.6.6"
chrono = "0.4"
debug-cell = "0.1"
derivative = "2.2"
dyn-clone = "1.0.20"
env_logger = "0.10"
itertools = "0.12.1"
lazy_static = "1.5.0"
linked-hash-map = "0.5"
linked_hash_set = "0.1.6"
log = "0.4"
num_cpus = "1.17"
pad = "0.1"
pathdiff = "0.2"
quick-xml = "0.36"
rand = "0.9.5"
rayon = "1.12.0"
regex = "1.13"
rust-embed = "8.12"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
strum = "0.24"
strum_macros = "0.24"
tempdir = "0.3"
test_bin = "0.4"
test-log = "0.2"
toml = "0.8"
walkdir = "2.5"

