[package]
name = "breakout"
version = "1.0.0"
source_folder = "."
main = "breakout.rasm"
resource_folder = "."
out = "breakout"

[dependencies]
stdlib = { path = "../../../../stdlib" }
sdl = { path = "../sdl" }