[package]
name = "rasm-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# workspace
linked-hash-map.workspace = true
log.workspace = true
env_logger.workspace = true