[package]
name = "showimage"
version = "1.0.0"
main = "showimage.rasm"

[dependencies]
stdlib = { path = "../../../../stdlib" }
sdl = { path = "../sdl" }

[targets.nasmi386]
externals = [
    "printf",
    "exit"
]