[package]
name = "showimage"
version = "1.0.0"
main = "showimage.rasm"
out = "showimage"

[dependencies]
stdlib = { path = "../../../../stdlib" }
sdl = { path = "../sdl" }

[natives]
[natives.nasmi386]
externals = [
    "printf",
    "exit"
]