[package]
name = "rasm-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# local deps
rasm-core.workspace = true
rasm-parser.workspace = true

# others
iced = "0.13.1"