name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libc++-dev
      - name: Run tests
        run: cargo test --verbose
