name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libc++-dev nasm libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
      - name: Run tests
        run: RUST_BACKTRACE=full cargo test --verbose --workspace
