[package]
name = "gameoflife_iter_sdl"
version = "1.0.0"
main = "gameoflife_iter_sdl.rasm"
out = "gameoflife_iter_sdl"

[dependencies]
stdlib = { path = "../../../../stdlib" }
sdl = { path = "../sdl" }